# Hikari Config
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    org.springframework.jdbc: DEBUG


# PostgresSQL
spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    hibernate:
      ddl-auto: update
