name: Build

on:
  push:
    branches: [ "master", "feature-*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -DDB_URL=${{secrets.DB_URL}} -DDB_PORT=${{secrets.DB_PORT}} -DDB_NAME=${{secrets.DB_NAME}} -B package --file pom.xml
