name: Build

on:
  push:
    branches: [ "master", "feature-*", "dev"]
  pull_request:
    branches: [ "master", "dev"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -DDB_URL=${{secrets.DB_URL}} -DDB_PORT=${{secrets.DB_PORT}} -DDB_NAME=${{secrets.DB_NAME}} -DDB_USERNAME=${{secrets.DB_USERNAME}} -DDB_PASSWORD=${{secrets.DB_PASSWORD}} -DMAIL_HOST=${{secrets.MAIL_HOST}} -DMAIL_USERNAME=${{secrets.MAIL_USERNAME}} -DMAIL_PASSWORD=${{secrets.MAIL_PASSWORD}} -B package --file pom.xml
