name: docker-compose

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  api_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d

    - name: Stop and remove Docker Compose services
      run: |
        docker-compose down
